"""
Oracle 테이블 생성 DDL
TB_PLAN_DATA 및 하위 상세 테이블
"""

# ==================== TB_PLAN_DATA (마스터 테이블) ====================
CREATE_TB_PLAN_DATA = """
CREATE TABLE TB_PLAN_DATA (
    PLAN_ID CHAR(30) NOT NULL PRIMARY KEY,
    YEAR NUMBER,
    NUM NUMBER,
    NATION_ORGAN_NM VARCHAR2(768),
    DETAIL_BIZ_NM VARCHAR2(768),
    BIZ_NM VARCHAR2(768),
    BIZ_TYPE VARCHAR2(768),
    AREA VARCHAR2(768),
    REP_FLD VARCHAR2(768),
    BIOLOGY_WEI NUMBER,
    RED_WEI NUMBER,
    GREEN_WEI NUMBER,
    WHITE_WEI NUMBER,
    FUSION_WEI NUMBER,
    LEAD_ORGAN_NM VARCHAR2(768),
    MNG_ORGAN_NM VARCHAR2(768),
    BIZ_SDT DATE,
    BIZ_EDT DATE,
    RESPERIOD VARCHAR2(768),
    CUR_RESPERIOD VARCHAR2(768),
    TOTAL_RESPRC VARCHAR2(768),
    TOTAL_RESPRC_GOV NUMBER,
    TOTAL_RESPRC_CIV NUMBER,
    CUR_RESPRC VARCHAR2(768),
    CUR_RESPRC_GOV NUMBER,
    CUR_RESPRC_CIV NUMBER,
    LAST_GOAL VARCHAR2(4000),
    BIZ_CONTENTS VARCHAR2(4000),
    BIZ_CONTENTS_KEYWORD VARCHAR2(4000),
    REGIST_DT DATE DEFAULT SYSDATE,
    DELETE_YN CHAR(1) DEFAULT 'N',
    DELETE_ID VARCHAR2(20),
    DELETE_DT DATE,
    REGIST_ID VARCHAR2(320),
    MODIFY_ID VARCHAR2(320),
    MODIFY_DT DATE,
    REGUL_WEI NUMBER,
    WEI VARCHAR2(768),
    PERFORM_PRC NUMBER,
    PLAN_PRC NUMBER
)
"""

COMMENT_TB_PLAN_DATA = [
    "COMMENT ON COLUMN TB_PLAN_DATA.PLAN_ID IS '시행계획 아이디'",
    "COMMENT ON COLUMN TB_PLAN_DATA.YEAR IS '년도'",
    "COMMENT ON COLUMN TB_PLAN_DATA.NUM IS '순번'",
    "COMMENT ON COLUMN TB_PLAN_DATA.NATION_ORGAN_NM IS '부처명'",
    "COMMENT ON COLUMN TB_PLAN_DATA.DETAIL_BIZ_NM IS '상세 사업 명'",
    "COMMENT ON COLUMN TB_PLAN_DATA.BIZ_NM IS '사업 명'",
    "COMMENT ON COLUMN TB_PLAN_DATA.BIZ_TYPE IS '사업 유형'",
    "COMMENT ON COLUMN TB_PLAN_DATA.AREA IS '3대영역'",
    "COMMENT ON COLUMN TB_PLAN_DATA.REP_FLD IS '대표 분야'",
    "COMMENT ON COLUMN TB_PLAN_DATA.BIOLOGY_WEI IS '생명과학 비중'",
    "COMMENT ON COLUMN TB_PLAN_DATA.RED_WEI IS '레드 비중'",
    "COMMENT ON COLUMN TB_PLAN_DATA.GREEN_WEI IS '그린 비중'",
    "COMMENT ON COLUMN TB_PLAN_DATA.WHITE_WEI IS '화이트 비중'",
    "COMMENT ON COLUMN TB_PLAN_DATA.FUSION_WEI IS '융합 비중'",
    "COMMENT ON COLUMN TB_PLAN_DATA.LEAD_ORGAN_NM IS '주관 기관 명'",
    "COMMENT ON COLUMN TB_PLAN_DATA.MNG_ORGAN_NM IS '관리 기관 명'",
    "COMMENT ON COLUMN TB_PLAN_DATA.BIZ_SDT IS '사업 시작일'",
    "COMMENT ON COLUMN TB_PLAN_DATA.BIZ_EDT IS '사업 종료일'",
    "COMMENT ON COLUMN TB_PLAN_DATA.RESPERIOD IS '연구기간'",
    "COMMENT ON COLUMN TB_PLAN_DATA.CUR_RESPERIOD IS '현 연구기간'",
    "COMMENT ON COLUMN TB_PLAN_DATA.TOTAL_RESPRC IS '총 연구비'",
    "COMMENT ON COLUMN TB_PLAN_DATA.TOTAL_RESPRC_GOV IS '총 연구비 정부'",
    "COMMENT ON COLUMN TB_PLAN_DATA.TOTAL_RESPRC_CIV IS '총 연구비 민간'",
    "COMMENT ON COLUMN TB_PLAN_DATA.CUR_RESPRC IS '현 연구비'",
    "COMMENT ON COLUMN TB_PLAN_DATA.CUR_RESPRC_GOV IS '현 연구비 정부'",
    "COMMENT ON COLUMN TB_PLAN_DATA.CUR_RESPRC_CIV IS '현 연구비 민간'",
    "COMMENT ON COLUMN TB_PLAN_DATA.LAST_GOAL IS '최종 목표'",
    "COMMENT ON COLUMN TB_PLAN_DATA.BIZ_CONTENTS IS '사업 내용'",
    "COMMENT ON COLUMN TB_PLAN_DATA.BIZ_CONTENTS_KEYWORD IS '사업 내용 키워드'",
    "COMMENT ON COLUMN TB_PLAN_DATA.REGIST_DT IS '등록 일자'",
    "COMMENT ON COLUMN TB_PLAN_DATA.DELETE_YN IS '삭제 유무'",
    "COMMENT ON COLUMN TB_PLAN_DATA.DELETE_ID IS '삭제 아이디'",
    "COMMENT ON COLUMN TB_PLAN_DATA.DELETE_DT IS '삭제 일자'",
    "COMMENT ON COLUMN TB_PLAN_DATA.REGIST_ID IS '등록 아이디'",
    "COMMENT ON COLUMN TB_PLAN_DATA.MODIFY_ID IS '수정 아이디'",
    "COMMENT ON COLUMN TB_PLAN_DATA.MODIFY_DT IS '수정 일자'",
    "COMMENT ON COLUMN TB_PLAN_DATA.REGUL_WEI IS '규제 비중'",
    "COMMENT ON COLUMN TB_PLAN_DATA.WEI IS '비중'",
    "COMMENT ON COLUMN TB_PLAN_DATA.PERFORM_PRC IS '실적 비용'",
    "COMMENT ON COLUMN TB_PLAN_DATA.PLAN_PRC IS '계획 비용'"
]


# ==================== TB_PLAN_SCHEDULES (일정 상세) ====================
CREATE_TB_PLAN_SCHEDULES = """
CREATE TABLE TB_PLAN_SCHEDULES (
    SCHEDULE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PLAN_ID CHAR(30) NOT NULL,
    YEAR NUMBER,
    QUARTER NUMBER,
    MONTH_START NUMBER,
    MONTH_END NUMBER,
    START_DATE DATE,
    END_DATE DATE,
    TASK_CATEGORY VARCHAR2(200),
    TASK_DESCRIPTION CLOB,
    ORIGINAL_PERIOD VARCHAR2(100),
    REGIST_DT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_SCHEDULES_PLAN FOREIGN KEY (PLAN_ID) 
        REFERENCES TB_PLAN_DATA(PLAN_ID) ON DELETE CASCADE
)
"""

COMMENT_TB_PLAN_SCHEDULES = [
    "COMMENT ON COLUMN TB_PLAN_SCHEDULES.SCHEDULE_ID IS '일정 아이디'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULES.PLAN_ID IS '시행계획 아이디'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULES.YEAR IS '년도'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULES.QUARTER IS '분기'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULES.MONTH_START IS '시작 월'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULES.MONTH_END IS '종료 월'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULES.START_DATE IS '시작일'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULES.END_DATE IS '종료일'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULES.TASK_CATEGORY IS '업무 분류'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULES.TASK_DESCRIPTION IS '업무 설명'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULES.ORIGINAL_PERIOD IS '원본 기간'"
]


# ==================== TB_PLAN_PERFORMANCES (성과 상세) ====================
CREATE_TB_PLAN_PERFORMANCES = """
CREATE TABLE TB_PLAN_PERFORMANCES (
    PERFORMANCE_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PLAN_ID CHAR(30) NOT NULL,
    PERFORMANCE_YEAR NUMBER,
    INDICATOR_CATEGORY VARCHAR2(100),
    INDICATOR_TYPE VARCHAR2(200),
    VALUE NUMBER,
    UNIT VARCHAR2(50),
    ORIGINAL_TEXT CLOB,
    REGIST_DT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_PERFORMANCES_PLAN FOREIGN KEY (PLAN_ID) 
        REFERENCES TB_PLAN_DATA(PLAN_ID) ON DELETE CASCADE
)
"""

COMMENT_TB_PLAN_PERFORMANCES = [
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCES.PERFORMANCE_ID IS '성과 아이디'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCES.PLAN_ID IS '시행계획 아이디'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCES.PERFORMANCE_YEAR IS '성과 년도'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCES.INDICATOR_CATEGORY IS '지표 분류'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCES.INDICATOR_TYPE IS '지표 유형'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCES.VALUE IS '값'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCES.UNIT IS '단위'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCES.ORIGINAL_TEXT IS '원본 텍스트'"
]


# ==================== TB_PLAN_BUDGETS (예산 상세) ====================
CREATE_TB_PLAN_BUDGETS = """
CREATE TABLE TB_PLAN_BUDGETS (
    BUDGET_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PLAN_ID CHAR(30) NOT NULL,
    BUDGET_YEAR NUMBER,
    BUDGET_CATEGORY VARCHAR2(100),
    BUDGET_TYPE VARCHAR2(100),
    AMOUNT NUMBER(15, 2),
    CURRENCY VARCHAR2(10) DEFAULT 'KRW',
    IS_ACTUAL CHAR(1) DEFAULT 'N',
    ORIGINAL_TEXT CLOB,
    REGIST_DT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_BUDGETS_PLAN FOREIGN KEY (PLAN_ID) 
        REFERENCES TB_PLAN_DATA(PLAN_ID) ON DELETE CASCADE
)
"""

COMMENT_TB_PLAN_BUDGETS = [
    "COMMENT ON COLUMN TB_PLAN_BUDGETS.BUDGET_ID IS '예산 아이디'",
    "COMMENT ON COLUMN TB_PLAN_BUDGETS.PLAN_ID IS '시행계획 아이디'",
    "COMMENT ON COLUMN TB_PLAN_BUDGETS.BUDGET_YEAR IS '예산 년도'",
    "COMMENT ON COLUMN TB_PLAN_BUDGETS.BUDGET_CATEGORY IS '예산 분류'",
    "COMMENT ON COLUMN TB_PLAN_BUDGETS.BUDGET_TYPE IS '예산 유형'",
    "COMMENT ON COLUMN TB_PLAN_BUDGETS.AMOUNT IS '금액'",
    "COMMENT ON COLUMN TB_PLAN_BUDGETS.CURRENCY IS '통화'",
    "COMMENT ON COLUMN TB_PLAN_BUDGETS.IS_ACTUAL IS '실적 여부'",
    "COMMENT ON COLUMN TB_PLAN_BUDGETS.ORIGINAL_TEXT IS '원본 텍스트'"
]


# ==================== TB_PLAN_ACHIEVEMENTS (대표성과) ====================
CREATE_TB_PLAN_ACHIEVEMENTS = """
CREATE TABLE TB_PLAN_ACHIEVEMENTS (
    ACHIEVEMENT_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PLAN_ID CHAR(30) NOT NULL,
    ACHIEVEMENT_YEAR NUMBER,
    ACHIEVEMENT_ORDER NUMBER,
    DESCRIPTION CLOB,
    REGIST_DT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_ACHIEVEMENTS_PLAN FOREIGN KEY (PLAN_ID) 
        REFERENCES TB_PLAN_DATA(PLAN_ID) ON DELETE CASCADE
)
"""

COMMENT_TB_PLAN_ACHIEVEMENTS = [
    "COMMENT ON COLUMN TB_PLAN_ACHIEVEMENTS.ACHIEVEMENT_ID IS '성과 아이디'",
    "COMMENT ON COLUMN TB_PLAN_ACHIEVEMENTS.PLAN_ID IS '시행계획 아이디'",
    "COMMENT ON COLUMN TB_PLAN_ACHIEVEMENTS.ACHIEVEMENT_YEAR IS '성과 년도'",
    "COMMENT ON COLUMN TB_PLAN_ACHIEVEMENTS.ACHIEVEMENT_ORDER IS '성과 순서'",
    "COMMENT ON COLUMN TB_PLAN_ACHIEVEMENTS.DESCRIPTION IS '성과 내용'"
]


# ==================== TB_PLAN_DETAILS (추진계획 상세) ====================
CREATE_TB_PLAN_DETAILS = """
CREATE TABLE TB_PLAN_DETAILS (
    DETAIL_ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PLAN_ID CHAR(30) NOT NULL,
    PLAN_YEAR NUMBER,
    PLAN_ORDER NUMBER,
    DESCRIPTION CLOB,
    REGIST_DT DATE DEFAULT SYSDATE,
    CONSTRAINT FK_DETAILS_PLAN FOREIGN KEY (PLAN_ID) 
        REFERENCES TB_PLAN_DATA(PLAN_ID) ON DELETE CASCADE
)
"""

COMMENT_TB_PLAN_DETAILS = [
    "COMMENT ON COLUMN TB_PLAN_DETAILS.DETAIL_ID IS '상세 아이디'",
    "COMMENT ON COLUMN TB_PLAN_DETAILS.PLAN_ID IS '시행계획 아이디'",
    "COMMENT ON COLUMN TB_PLAN_DETAILS.PLAN_YEAR IS '계획 년도'",
    "COMMENT ON COLUMN TB_PLAN_DETAILS.PLAN_ORDER IS '계획 순서'",
    "COMMENT ON COLUMN TB_PLAN_DETAILS.DESCRIPTION IS '계획 내용'"
]


# ==================== 인덱스 생성 ====================
CREATE_INDEXES = [
    # TB_PLAN_DATA 인덱스
    "CREATE INDEX IDX_PLAN_YEAR ON TB_PLAN_DATA(YEAR)",
    "CREATE INDEX IDX_PLAN_DEPT ON TB_PLAN_DATA(NATION_ORGAN_NM)",
    "CREATE INDEX IDX_PLAN_BIZ ON TB_PLAN_DATA(BIZ_NM)",

    # TB_PLAN_SCHEDULES 인덱스
    "CREATE INDEX IDX_SCHEDULE_YEAR ON TB_PLAN_SCHEDULES(YEAR)",
    "CREATE INDEX IDX_SCHEDULE_QUARTER ON TB_PLAN_SCHEDULES(QUARTER)",

    # TB_PLAN_PERFORMANCES 인덱스
    "CREATE INDEX IDX_PERF_YEAR ON TB_PLAN_PERFORMANCES(PERFORMANCE_YEAR)",
    "CREATE INDEX IDX_PERF_CATEGORY ON TB_PLAN_PERFORMANCES(INDICATOR_CATEGORY)",

    # TB_PLAN_BUDGETS 인덱스
    "CREATE INDEX IDX_BUDGET_YEAR ON TB_PLAN_BUDGETS(BUDGET_YEAR)",
    "CREATE INDEX IDX_BUDGET_CATEGORY ON TB_PLAN_BUDGETS(BUDGET_CATEGORY)",

    # TB_PLAN_ACHIEVEMENTS 인덱스
    "CREATE INDEX IDX_ACHIEVE_YEAR ON TB_PLAN_ACHIEVEMENTS(ACHIEVEMENT_YEAR)",

    # TB_PLAN_DETAILS 인덱스
    "CREATE INDEX IDX_DETAIL_YEAR ON TB_PLAN_DETAILS(PLAN_YEAR)"
]


# ==================== 테이블 목록 (생성 순서) ====================
TABLE_DEFINITIONS = [
    ('TB_PLAN_DATA', CREATE_TB_PLAN_DATA, COMMENT_TB_PLAN_DATA),
    ('TB_PLAN_SCHEDULES', CREATE_TB_PLAN_SCHEDULES, COMMENT_TB_PLAN_SCHEDULES),
    ('TB_PLAN_PERFORMANCES', CREATE_TB_PLAN_PERFORMANCES, COMMENT_TB_PLAN_PERFORMANCES),
    ('TB_PLAN_BUDGETS', CREATE_TB_PLAN_BUDGETS, COMMENT_TB_PLAN_BUDGETS),
    ('TB_PLAN_ACHIEVEMENTS', CREATE_TB_PLAN_ACHIEVEMENTS, COMMENT_TB_PLAN_ACHIEVEMENTS),
    ('TB_PLAN_DETAILS', CREATE_TB_PLAN_DETAILS, COMMENT_TB_PLAN_DETAILS)
]

