"""
생명공학 시행계획 테이블 DDL
회사 기존 TB_PLAN_DATA + 하위 테이블 4개
"""

# ==================== 1. TB_PLAN_DATA (회사 기존 메인 테이블) ====================
CREATE_TB_PLAN_DATA = """
CREATE TABLE TB_PLAN_DATA (
    PLAN_ID             CHAR(30) PRIMARY KEY,
    YEAR                NUMBER(4),
    NUM                 NUMBER,
    NATION_ORGAN_NM     VARCHAR2(768),
    DETAIL_BIZ_NM       VARCHAR2(768),
    BIZ_NM              VARCHAR2(768),
    BIZ_TYPE            VARCHAR2(768),
    AREA                VARCHAR2(768),
    REP_FLD             VARCHAR2(768),
    BIOLOGY_WEI         NUMBER,
    RED_WEI             NUMBER,
    GREEN_WEI           NUMBER,
    WHITE_WEI           NUMBER,
    FUSION_WEI          NUMBER,
    LEAD_ORGAN_NM       VARCHAR2(768),
    MNG_ORGAN_NM        VARCHAR2(768),
    BIZ_SDT             DATE,
    BIZ_EDT             DATE,
    RESPERIOD           VARCHAR2(768),
    CUR_RESPERIOD       VARCHAR2(768),
    TOTAL_RESPRC        VARCHAR2(768),
    TOTAL_RESPRC_GOV    NUMBER,
    TOTAL_RESPRC_CIV    NUMBER,
    CUR_RESPRC          VARCHAR2(768),
    CUR_RESPRC_GOV      NUMBER,
    CUR_RESPRC_CIV      NUMBER,
    LAST_GOAL           VARCHAR2(4000),
    BIZ_CONTENTS        VARCHAR2(4000),
    BIZ_CONTENTS_KEYWORD VARCHAR2(4000),
    REGIST_DT           DATE DEFAULT SYSDATE,
    DELETE_YN           CHAR(1) DEFAULT 'N',
    DELETE_ID           VARCHAR2(20),
    DELETE_DT           DATE,
    REGIST_ID           VARCHAR2(320),
    MODIFY_ID           VARCHAR2(320),
    MODIFY_DT           DATE,
    REGUL_WEI           NUMBER,
    WEI                 VARCHAR2(768),
    PERFORM_PRC         NUMBER,
    PLAN_PRC            NUMBER
)
"""

COMMENT_TB_PLAN_DATA = [
    "COMMENT ON TABLE TB_PLAN_DATA IS '시행계획 메인 테이블'",
    "COMMENT ON COLUMN TB_PLAN_DATA.PLAN_ID IS '시행계획 아이디 (PK)'",
    "COMMENT ON COLUMN TB_PLAN_DATA.YEAR IS '년도'",
    "COMMENT ON COLUMN TB_PLAN_DATA.NUM IS '순번'",
    "COMMENT ON COLUMN TB_PLAN_DATA.NATION_ORGAN_NM IS '부처명'",
    "COMMENT ON COLUMN TB_PLAN_DATA.DETAIL_BIZ_NM IS '내역사업명'",
    "COMMENT ON COLUMN TB_PLAN_DATA.BIZ_NM IS '사업명'",
    "COMMENT ON COLUMN TB_PLAN_DATA.BIZ_TYPE IS '사업 유형'",
    "COMMENT ON COLUMN TB_PLAN_DATA.AREA IS '3대영역'",
    "COMMENT ON COLUMN TB_PLAN_DATA.REP_FLD IS '대표 분야'",
    "COMMENT ON COLUMN TB_PLAN_DATA.BIOLOGY_WEI IS '생명과학 비중'",
    "COMMENT ON COLUMN TB_PLAN_DATA.RED_WEI IS '레드 비중'",
    "COMMENT ON COLUMN TB_PLAN_DATA.GREEN_WEI IS '그린 비중'",
    "COMMENT ON COLUMN TB_PLAN_DATA.WHITE_WEI IS '화이트 비중'",
    "COMMENT ON COLUMN TB_PLAN_DATA.FUSION_WEI IS '융합 비중'",
    "COMMENT ON COLUMN TB_PLAN_DATA.LEAD_ORGAN_NM IS '주관 기관명'",
    "COMMENT ON COLUMN TB_PLAN_DATA.MNG_ORGAN_NM IS '관리 기관명'",
    "COMMENT ON COLUMN TB_PLAN_DATA.BIZ_SDT IS '사업 시작일'",
    "COMMENT ON COLUMN TB_PLAN_DATA.BIZ_EDT IS '사업 종료일'",
    "COMMENT ON COLUMN TB_PLAN_DATA.RESPERIOD IS '연구기간'",
    "COMMENT ON COLUMN TB_PLAN_DATA.CUR_RESPERIOD IS '현 연구기간'",
    "COMMENT ON COLUMN TB_PLAN_DATA.TOTAL_RESPRC IS '총 연구비'",
    "COMMENT ON COLUMN TB_PLAN_DATA.TOTAL_RESPRC_GOV IS '총 연구비 정부'",
    "COMMENT ON COLUMN TB_PLAN_DATA.TOTAL_RESPRC_CIV IS '총 연구비 민간'",
    "COMMENT ON COLUMN TB_PLAN_DATA.CUR_RESPRC IS '현 연구비'",
    "COMMENT ON COLUMN TB_PLAN_DATA.CUR_RESPRC_GOV IS '현 연구비 정부'",
    "COMMENT ON COLUMN TB_PLAN_DATA.CUR_RESPRC_CIV IS '현 연구비 민간'",
    "COMMENT ON COLUMN TB_PLAN_DATA.LAST_GOAL IS '최종 목표'",
    "COMMENT ON COLUMN TB_PLAN_DATA.BIZ_CONTENTS IS '사업 내용'",
    "COMMENT ON COLUMN TB_PLAN_DATA.BIZ_CONTENTS_KEYWORD IS '사업 내용 키워드'",
    "COMMENT ON COLUMN TB_PLAN_DATA.REGIST_DT IS '등록 일자'",
    "COMMENT ON COLUMN TB_PLAN_DATA.DELETE_YN IS '삭제 유무'",
    "COMMENT ON COLUMN TB_PLAN_DATA.REGUL_WEI IS '규제 비중'",
    "COMMENT ON COLUMN TB_PLAN_DATA.WEI IS '비중'",
    "COMMENT ON COLUMN TB_PLAN_DATA.PERFORM_PRC IS '실적 비용'",
    "COMMENT ON COLUMN TB_PLAN_DATA.PLAN_PRC IS '계획 비용'",
]


# ==================== 2. TB_PLAN_BUDGET (예산 상세 - 1:N) ====================
CREATE_TB_PLAN_BUDGET = """
CREATE TABLE TB_PLAN_BUDGET (
    BUDGET_ID       CHAR(30) PRIMARY KEY,
    PLAN_ID         CHAR(30) NOT NULL,
    
    BUDGET_YEAR     NUMBER(4) NOT NULL,
    CATEGORY        VARCHAR2(50),
    
    TOTAL_AMOUNT    NUMBER,
    GOV_AMOUNT      NUMBER,
    PRIVATE_AMOUNT  NUMBER,
    LOCAL_AMOUNT    NUMBER,
    ETC_AMOUNT      NUMBER,
    
    PERFORM_PRC     NUMBER,
    PLAN_PRC        NUMBER,
    
    REGIST_DT       DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_BUDGET_PLAN FOREIGN KEY (PLAN_ID) 
        REFERENCES TB_PLAN_DATA(PLAN_ID) ON DELETE CASCADE
)
"""

COMMENT_TB_PLAN_BUDGET = [
    "COMMENT ON TABLE TB_PLAN_BUDGET IS '시행계획 예산 상세 (연도별, 실적/계획 구분)'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.BUDGET_ID IS '예산 아이디 (PK)'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.PLAN_ID IS '시행계획 아이디 (FK)'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.BUDGET_YEAR IS '예산 연도'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.CATEGORY IS '구분 (실적/계획)'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.TOTAL_AMOUNT IS '총액 (백만원)'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.GOV_AMOUNT IS '정부 예산'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.PRIVATE_AMOUNT IS '민간 예산'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.LOCAL_AMOUNT IS '지방비'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.ETC_AMOUNT IS '기타'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.PERFORM_PRC IS '실적 비용'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.PLAN_PRC IS '계획 비용'",
]

# ==================== 3. TB_PLAN_SCHEDULE (일정 상세 - 1:N) ====================
CREATE_TB_PLAN_SCHEDULE = """
CREATE TABLE TB_PLAN_SCHEDULE (
    SCHEDULE_ID     CHAR(30) PRIMARY KEY,
    PLAN_ID         CHAR(30) NOT NULL,
    
    SCHEDULE_YEAR   NUMBER(4),
    QUARTER         VARCHAR2(50),
    
    TASK_NAME       VARCHAR2(768),
    TASK_CONTENT    VARCHAR2(4000),
    
    START_DATE      DATE,
    END_DATE        DATE,
    
    REGIST_DT       DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_SCHEDULE_PLAN FOREIGN KEY (PLAN_ID) 
        REFERENCES TB_PLAN_DATA(PLAN_ID) ON DELETE CASCADE
)
"""

COMMENT_TB_PLAN_SCHEDULE = [
    "COMMENT ON TABLE TB_PLAN_SCHEDULE IS '시행계획 일정 상세'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.SCHEDULE_ID IS '일정 아이디 (PK)'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.PLAN_ID IS '시행계획 아이디 (FK)'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.SCHEDULE_YEAR IS '일정 연도'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.QUARTER IS '분기'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.TASK_NAME IS '과제명'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.TASK_CONTENT IS '세부 내용'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.START_DATE IS '시작일'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.END_DATE IS '종료일'",
]

# ==================== 4. TB_PLAN_PERFORMANCE (성과 상세 - 1:N) ====================
CREATE_TB_PLAN_PERFORMANCE = """
CREATE TABLE TB_PLAN_PERFORMANCE (
    PERFORMANCE_ID  CHAR(30) PRIMARY KEY,
    PLAN_ID         CHAR(30) NOT NULL,
    
    PERFORMANCE_YEAR NUMBER(4),
    PERFORMANCE_TYPE VARCHAR2(100),
    CATEGORY        VARCHAR2(200),
    
    VALUE           NUMBER,
    UNIT            VARCHAR2(50),
    
    ORIGINAL_TEXT   VARCHAR2(4000),
    
    REGIST_DT       DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_PERFORMANCE_PLAN FOREIGN KEY (PLAN_ID) 
        REFERENCES TB_PLAN_DATA(PLAN_ID) ON DELETE CASCADE
)
"""

COMMENT_TB_PLAN_PERFORMANCE = [
    "COMMENT ON TABLE TB_PLAN_PERFORMANCE IS '시행계획 성과 상세 (특허, 논문, 인력양성 등)'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.PERFORMANCE_ID IS '성과 아이디 (PK)'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.PLAN_ID IS '시행계획 아이디 (FK)'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.PERFORMANCE_YEAR IS '실적 연도'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.PERFORMANCE_TYPE IS '성과 유형 (특허/논문/인력양성)'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.CATEGORY IS '세부 항목 (국내출원/SCIE/박사 등)'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.VALUE IS '실적 값'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.UNIT IS '단위 (건/명/편)'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.ORIGINAL_TEXT IS '원본 텍스트'",
]

# ==================== 5. TB_PLAN_ACHIEVEMENTS (대표성과 - 1:N) ====================
CREATE_TB_PLAN_ACHIEVEMENTS = """
CREATE TABLE TB_PLAN_ACHIEVEMENTS (
    ACHIEVEMENT_ID  CHAR(30) PRIMARY KEY,
    PLAN_ID         CHAR(30) NOT NULL,
    
    ACHIEVEMENT_YEAR NUMBER(4),
    ACHIEVEMENT_ORDER NUMBER,
    DESCRIPTION     VARCHAR2(4000),
    
    REGIST_DT       DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_ACHIEVEMENT_PLAN FOREIGN KEY (PLAN_ID) 
        REFERENCES TB_PLAN_DATA(PLAN_ID) ON DELETE CASCADE
)
"""

COMMENT_TB_PLAN_ACHIEVEMENTS = [
    "COMMENT ON TABLE TB_PLAN_ACHIEVEMENTS IS '시행계획 대표성과'",
    "COMMENT ON COLUMN TB_PLAN_ACHIEVEMENTS.ACHIEVEMENT_ID IS '대표성과 아이디 (PK)'",
    "COMMENT ON COLUMN TB_PLAN_ACHIEVEMENTS.PLAN_ID IS '시행계획 아이디 (FK)'",
    "COMMENT ON COLUMN TB_PLAN_ACHIEVEMENTS.ACHIEVEMENT_YEAR IS '실적 연도'",
    "COMMENT ON COLUMN TB_PLAN_ACHIEVEMENTS.ACHIEVEMENT_ORDER IS '순서'",
    "COMMENT ON COLUMN TB_PLAN_ACHIEVEMENTS.DESCRIPTION IS '성과 내용'",
]


# ==================== 인덱스 생성 ====================
CREATE_INDEXES = [
    # TB_PLAN_DATA 인덱스 (검색 최적화)
    "CREATE INDEX IDX_PLAN_YEAR ON TB_PLAN_DATA(YEAR)",
    "CREATE INDEX IDX_PLAN_DEPT ON TB_PLAN_DATA(NATION_ORGAN_NM)",
    "CREATE INDEX IDX_PLAN_BIZ ON TB_PLAN_DATA(BIZ_NM)",
    "CREATE INDEX IDX_PLAN_DETAIL_BIZ ON TB_PLAN_DATA(DETAIL_BIZ_NM)",

    # TB_PLAN_BUDGET 인덱스
    "CREATE INDEX IDX_BUDGET_PLAN ON TB_PLAN_BUDGET(PLAN_ID)",
    "CREATE INDEX IDX_BUDGET_YEAR ON TB_PLAN_BUDGET(BUDGET_YEAR)",
    "CREATE INDEX IDX_BUDGET_CATEGORY ON TB_PLAN_BUDGET(CATEGORY)",

    # TB_PLAN_SCHEDULE 인덱스
    "CREATE INDEX IDX_SCHEDULE_PLAN ON TB_PLAN_SCHEDULE(PLAN_ID)",
    "CREATE INDEX IDX_SCHEDULE_YEAR ON TB_PLAN_SCHEDULE(SCHEDULE_YEAR)",

    # TB_PLAN_PERFORMANCE 인덱스
    "CREATE INDEX IDX_PERFORMANCE_PLAN ON TB_PLAN_PERFORMANCE(PLAN_ID)",
    "CREATE INDEX IDX_PERFORMANCE_YEAR ON TB_PLAN_PERFORMANCE(PERFORMANCE_YEAR)",
    "CREATE INDEX IDX_PERFORMANCE_TYPE ON TB_PLAN_PERFORMANCE(PERFORMANCE_TYPE)",

    # TB_PLAN_ACHIEVEMENTS 인덱스
    "CREATE INDEX IDX_ACHIEVEMENT_PLAN ON TB_PLAN_ACHIEVEMENTS(PLAN_ID)",
    "CREATE INDEX IDX_ACHIEVEMENT_YEAR ON TB_PLAN_ACHIEVEMENTS(ACHIEVEMENT_YEAR)",
]

# ==================== 테이블 정의 딕셔너리 ====================
TABLE_DEFINITIONS = {
    'TB_PLAN_DATA': {
        'ddl': CREATE_TB_PLAN_DATA,
        'comments': COMMENT_TB_PLAN_DATA
    },
    'TB_PLAN_BUDGET': {
        'ddl': CREATE_TB_PLAN_BUDGET,
        'comments': COMMENT_TB_PLAN_BUDGET
    },
    'TB_PLAN_SCHEDULE': {
        'ddl': CREATE_TB_PLAN_SCHEDULE,
        'comments': COMMENT_TB_PLAN_SCHEDULE
    },
    'TB_PLAN_PERFORMANCE': {
        'ddl': CREATE_TB_PLAN_PERFORMANCE,
        'comments': COMMENT_TB_PLAN_PERFORMANCE
    },
    'TB_PLAN_ACHIEVEMENTS': {
        'ddl': CREATE_TB_PLAN_ACHIEVEMENTS,
        'comments': COMMENT_TB_PLAN_ACHIEVEMENTS
    }
}

# 테이블 생성 순서 (FK 의존성 고려)
TABLE_CREATE_ORDER = [
    'TB_PLAN_DATA',         # 1. 메인 (독립)
    'TB_PLAN_BUDGET',       # 2. 예산 상세
    'TB_PLAN_SCHEDULE',     # 3. 일정 상세
    'TB_PLAN_PERFORMANCE',  # 4. 성과 상세
    'TB_PLAN_ACHIEVEMENTS', # 5. 대표성과
]

# 테이블 삭제 순서 (FK 의존성 역순)
TABLE_DROP_ORDER = list(reversed(TABLE_CREATE_ORDER))



