"""
정규화된 생명공학 시행계획 테이블 DDL
완전 정규화 구조: 마스터 + 하위 테이블
"""

# ==================== 1. TB_PLAN_MASTER (마스터 테이블) ====================
CREATE_TB_PLAN_MASTER = """
CREATE TABLE TB_PLAN_MASTER (
    PLAN_ID         CHAR(30) PRIMARY KEY,
    YEAR            NUMBER(4) NOT NULL,
    NUM             NUMBER,
    NATION_ORGAN_NM VARCHAR2(768) NOT NULL,
    BIZ_NM          VARCHAR2(768) NOT NULL,
    DETAIL_BIZ_NM   VARCHAR2(768),
    
    REGIST_ID       VARCHAR2(320),
    REGIST_DT       DATE DEFAULT SYSDATE,
    MODIFY_ID       VARCHAR2(320),
    MODIFY_DT       DATE,
    DELETE_YN       CHAR(1) DEFAULT 'N',
    DELETE_ID       VARCHAR2(20),
    DELETE_DT       DATE
)
"""

COMMENT_TB_PLAN_MASTER = [
    "COMMENT ON TABLE TB_PLAN_MASTER IS '시행계획 마스터 테이블'",
    "COMMENT ON COLUMN TB_PLAN_MASTER.PLAN_ID IS '시행계획 아이디 (PK)'",
    "COMMENT ON COLUMN TB_PLAN_MASTER.YEAR IS '계획 년도'",
    "COMMENT ON COLUMN TB_PLAN_MASTER.NUM IS '순번'",
    "COMMENT ON COLUMN TB_PLAN_MASTER.NATION_ORGAN_NM IS '부처명'",
    "COMMENT ON COLUMN TB_PLAN_MASTER.BIZ_NM IS '세부사업명'",
    "COMMENT ON COLUMN TB_PLAN_MASTER.DETAIL_BIZ_NM IS '내역사업명'",
    "COMMENT ON COLUMN TB_PLAN_MASTER.REGIST_ID IS '등록자 아이디'",
    "COMMENT ON COLUMN TB_PLAN_MASTER.REGIST_DT IS '등록 일시'",
    "COMMENT ON COLUMN TB_PLAN_MASTER.MODIFY_ID IS '수정자 아이디'",
    "COMMENT ON COLUMN TB_PLAN_MASTER.MODIFY_DT IS '수정 일시'",
    "COMMENT ON COLUMN TB_PLAN_MASTER.DELETE_YN IS '삭제 여부 (Y/N)'",
]

# ==================== 2. TB_PLAN_DETAIL (사업 상세 정보) ====================
CREATE_TB_PLAN_DETAIL = """
CREATE TABLE TB_PLAN_DETAIL (
    DETAIL_ID       CHAR(30) PRIMARY KEY,
    PLAN_ID         CHAR(30) NOT NULL,
    
    BIZ_TYPE        VARCHAR2(768),
    REP_FLD         VARCHAR2(768),
    AREA            VARCHAR2(768),
    
    LEAD_ORGAN_NM   VARCHAR2(768),
    MNG_ORGAN_NM    VARCHAR2(768),
    
    BIZ_SDT         DATE,
    BIZ_EDT         DATE,
    RESPERIOD       VARCHAR2(768),
    CUR_RESPERIOD   VARCHAR2(768),
    
    LAST_GOAL       VARCHAR2(4000),
    BIZ_CONTENTS    VARCHAR2(4000),
    BIZ_CONTENTS_KEYWORD VARCHAR2(4000),
    
    CONSTRAINT FK_DETAIL_PLAN FOREIGN KEY (PLAN_ID) 
        REFERENCES TB_PLAN_MASTER(PLAN_ID) ON DELETE CASCADE
)
"""

COMMENT_TB_PLAN_DETAIL = [
    "COMMENT ON TABLE TB_PLAN_DETAIL IS '시행계획 상세 정보'",
    "COMMENT ON COLUMN TB_PLAN_DETAIL.DETAIL_ID IS '상세 아이디 (PK)'",
    "COMMENT ON COLUMN TB_PLAN_DETAIL.PLAN_ID IS '시행계획 아이디 (FK)'",
    "COMMENT ON COLUMN TB_PLAN_DETAIL.BIZ_TYPE IS '사업 유형'",
    "COMMENT ON COLUMN TB_PLAN_DETAIL.REP_FLD IS '대표 분야'",
    "COMMENT ON COLUMN TB_PLAN_DETAIL.AREA IS '3대 영역'",
    "COMMENT ON COLUMN TB_PLAN_DETAIL.LEAD_ORGAN_NM IS '주관 기관명'",
    "COMMENT ON COLUMN TB_PLAN_DETAIL.MNG_ORGAN_NM IS '관리 기관명'",
    "COMMENT ON COLUMN TB_PLAN_DETAIL.BIZ_SDT IS '사업 시작일'",
    "COMMENT ON COLUMN TB_PLAN_DETAIL.BIZ_EDT IS '사업 종료일'",
    "COMMENT ON COLUMN TB_PLAN_DETAIL.RESPERIOD IS '연구 기간'",
    "COMMENT ON COLUMN TB_PLAN_DETAIL.CUR_RESPERIOD IS '현재 연구 기간'",
    "COMMENT ON COLUMN TB_PLAN_DETAIL.LAST_GOAL IS '최종 목표'",
    "COMMENT ON COLUMN TB_PLAN_DETAIL.BIZ_CONTENTS IS '사업 내용'",
    "COMMENT ON COLUMN TB_PLAN_DETAIL.BIZ_CONTENTS_KEYWORD IS '사업 내용 키워드'",
]

# ==================== 3. TB_PLAN_BUDGET (예산 정보 - 1:N) ====================
CREATE_TB_PLAN_BUDGET = """
CREATE TABLE TB_PLAN_BUDGET (
    BUDGET_ID       CHAR(30) PRIMARY KEY,
    PLAN_ID         CHAR(30) NOT NULL,
    
    BUDGET_YEAR     NUMBER(4) NOT NULL,
    CATEGORY        VARCHAR2(50),
    
    TOTAL_AMOUNT    NUMBER,
    GOV_AMOUNT      NUMBER,
    PRIVATE_AMOUNT  NUMBER,
    LOCAL_AMOUNT    NUMBER,
    ETC_AMOUNT      NUMBER,
    
    PERFORM_PRC     NUMBER,
    PLAN_PRC        NUMBER,
    
    REGIST_DT       DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_BUDGET_PLAN FOREIGN KEY (PLAN_ID) 
        REFERENCES TB_PLAN_MASTER(PLAN_ID) ON DELETE CASCADE
)
"""

COMMENT_TB_PLAN_BUDGET = [
    "COMMENT ON TABLE TB_PLAN_BUDGET IS '시행계획 예산 정보 (연도별, 실적/계획 구분)'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.BUDGET_ID IS '예산 아이디 (PK)'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.PLAN_ID IS '시행계획 아이디 (FK)'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.BUDGET_YEAR IS '예산 연도'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.CATEGORY IS '구분 (실적/계획)'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.TOTAL_AMOUNT IS '총액 (백만원)'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.GOV_AMOUNT IS '정부 예산'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.PRIVATE_AMOUNT IS '민간 예산'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.LOCAL_AMOUNT IS '지방비'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.ETC_AMOUNT IS '기타'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.PERFORM_PRC IS '실적 비용'",
    "COMMENT ON COLUMN TB_PLAN_BUDGET.PLAN_PRC IS '계획 비용'",
]

# ==================== 4. TB_PLAN_SCHEDULE (일정 정보 - 1:N) ====================
CREATE_TB_PLAN_SCHEDULE = """
CREATE TABLE TB_PLAN_SCHEDULE (
    SCHEDULE_ID     CHAR(30) PRIMARY KEY,
    PLAN_ID         CHAR(30) NOT NULL,
    
    SCHEDULE_YEAR   NUMBER(4),
    QUARTER         VARCHAR2(50),
    
    TASK_NAME       VARCHAR2(768),
    TASK_CONTENT    VARCHAR2(4000),
    
    START_DATE      DATE,
    END_DATE        DATE,
    
    REGIST_DT       DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_SCHEDULE_PLAN FOREIGN KEY (PLAN_ID) 
        REFERENCES TB_PLAN_MASTER(PLAN_ID) ON DELETE CASCADE
)
"""

COMMENT_TB_PLAN_SCHEDULE = [
    "COMMENT ON TABLE TB_PLAN_SCHEDULE IS '시행계획 일정 정보'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.SCHEDULE_ID IS '일정 아이디 (PK)'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.PLAN_ID IS '시행계획 아이디 (FK)'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.SCHEDULE_YEAR IS '일정 연도'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.QUARTER IS '분기 (예: 1/4분기~2/4분기)'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.TASK_NAME IS '과제명'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.TASK_CONTENT IS '세부 내용'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.START_DATE IS '시작일'",
    "COMMENT ON COLUMN TB_PLAN_SCHEDULE.END_DATE IS '종료일'",
]

# ==================== 5. TB_PLAN_PERFORMANCE (성과 정보 - 1:N) ====================
CREATE_TB_PLAN_PERFORMANCE = """
CREATE TABLE TB_PLAN_PERFORMANCE (
    PERFORMANCE_ID  CHAR(30) PRIMARY KEY,
    PLAN_ID         CHAR(30) NOT NULL,
    
    PERFORMANCE_YEAR NUMBER(4),
    PERFORMANCE_TYPE VARCHAR2(100),
    CATEGORY        VARCHAR2(200),
    
    VALUE           NUMBER,
    UNIT            VARCHAR2(50),
    
    ORIGINAL_TEXT   VARCHAR2(4000),
    
    REGIST_DT       DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_PERFORMANCE_PLAN FOREIGN KEY (PLAN_ID) 
        REFERENCES TB_PLAN_MASTER(PLAN_ID) ON DELETE CASCADE
)
"""

COMMENT_TB_PLAN_PERFORMANCE = [
    "COMMENT ON TABLE TB_PLAN_PERFORMANCE IS '시행계획 성과 정보 (특허, 논문, 인력양성 등)'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.PERFORMANCE_ID IS '성과 아이디 (PK)'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.PLAN_ID IS '시행계획 아이디 (FK)'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.PERFORMANCE_YEAR IS '실적 연도'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.PERFORMANCE_TYPE IS '성과 유형 (특허/논문/인력양성)'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.CATEGORY IS '세부 항목 (국내출원/SCIE/박사 등)'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.VALUE IS '실적 값'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.UNIT IS '단위 (건/명/편)'",
    "COMMENT ON COLUMN TB_PLAN_PERFORMANCE.ORIGINAL_TEXT IS '원본 텍스트'",
]

# ==================== 6. TB_PLAN_WEIGHT (분야별 비중) ====================
CREATE_TB_PLAN_WEIGHT = """
CREATE TABLE TB_PLAN_WEIGHT (
    WEIGHT_ID       CHAR(30) PRIMARY KEY,
    PLAN_ID         CHAR(30) NOT NULL,
    
    BIOLOGY_WEI     NUMBER,
    RED_WEI         NUMBER,
    GREEN_WEI       NUMBER,
    WHITE_WEI       NUMBER,
    FUSION_WEI      NUMBER,
    REGUL_WEI       NUMBER,
    WEI             VARCHAR2(768),
    
    REGIST_DT       DATE DEFAULT SYSDATE,
    
    CONSTRAINT FK_WEIGHT_PLAN FOREIGN KEY (PLAN_ID) 
        REFERENCES TB_PLAN_MASTER(PLAN_ID) ON DELETE CASCADE
)
"""

COMMENT_TB_PLAN_WEIGHT = [
    "COMMENT ON TABLE TB_PLAN_WEIGHT IS '시행계획 분야별 비중'",
    "COMMENT ON COLUMN TB_PLAN_WEIGHT.WEIGHT_ID IS '비중 아이디 (PK)'",
    "COMMENT ON COLUMN TB_PLAN_WEIGHT.PLAN_ID IS '시행계획 아이디 (FK)'",
    "COMMENT ON COLUMN TB_PLAN_WEIGHT.BIOLOGY_WEI IS '생명과학 비중 (%)'",
    "COMMENT ON COLUMN TB_PLAN_WEIGHT.RED_WEI IS '레드 바이오 비중 (%)'",
    "COMMENT ON COLUMN TB_PLAN_WEIGHT.GREEN_WEI IS '그린 바이오 비중 (%)'",
    "COMMENT ON COLUMN TB_PLAN_WEIGHT.WHITE_WEI IS '화이트 바이오 비중 (%)'",
    "COMMENT ON COLUMN TB_PLAN_WEIGHT.FUSION_WEI IS '융합 비중 (%)'",
    "COMMENT ON COLUMN TB_PLAN_WEIGHT.REGUL_WEI IS '규제 비중 (%)'",
    "COMMENT ON COLUMN TB_PLAN_WEIGHT.WEI IS '기타 비중 정보'",
]

# ==================== 인덱스 생성 ====================
CREATE_INDEXES = [
    # TB_PLAN_MASTER 인덱스 (검색 최적화)
    "CREATE INDEX IDX_MASTER_YEAR ON TB_PLAN_MASTER(YEAR)",
    "CREATE INDEX IDX_MASTER_DEPT ON TB_PLAN_MASTER(NATION_ORGAN_NM)",
    "CREATE INDEX IDX_MASTER_BIZ ON TB_PLAN_MASTER(BIZ_NM)",
    "CREATE INDEX IDX_MASTER_DETAIL_BIZ ON TB_PLAN_MASTER(DETAIL_BIZ_NM)",

    # TB_PLAN_BUDGET 인덱스
    "CREATE INDEX IDX_BUDGET_PLAN ON TB_PLAN_BUDGET(PLAN_ID)",
    "CREATE INDEX IDX_BUDGET_YEAR ON TB_PLAN_BUDGET(BUDGET_YEAR)",
    "CREATE INDEX IDX_BUDGET_CATEGORY ON TB_PLAN_BUDGET(CATEGORY)",

    # TB_PLAN_SCHEDULE 인덱스
    "CREATE INDEX IDX_SCHEDULE_PLAN ON TB_PLAN_SCHEDULE(PLAN_ID)",
    "CREATE INDEX IDX_SCHEDULE_YEAR ON TB_PLAN_SCHEDULE(SCHEDULE_YEAR)",

    # TB_PLAN_PERFORMANCE 인덱스
    "CREATE INDEX IDX_PERFORMANCE_PLAN ON TB_PLAN_PERFORMANCE(PLAN_ID)",
    "CREATE INDEX IDX_PERFORMANCE_YEAR ON TB_PLAN_PERFORMANCE(PERFORMANCE_YEAR)",
    "CREATE INDEX IDX_PERFORMANCE_TYPE ON TB_PLAN_PERFORMANCE(PERFORMANCE_TYPE)",
]

# ==================== 테이블 정의 딕셔너리 ====================
TABLE_DEFINITIONS = {
    'TB_PLAN_MASTER': {
        'ddl': CREATE_TB_PLAN_MASTER,
        'comments': COMMENT_TB_PLAN_MASTER
    },
    'TB_PLAN_DETAIL': {
        'ddl': CREATE_TB_PLAN_DETAIL,
        'comments': COMMENT_TB_PLAN_DETAIL
    },
    'TB_PLAN_BUDGET': {
        'ddl': CREATE_TB_PLAN_BUDGET,
        'comments': COMMENT_TB_PLAN_BUDGET
    },
    'TB_PLAN_SCHEDULE': {
        'ddl': CREATE_TB_PLAN_SCHEDULE,
        'comments': COMMENT_TB_PLAN_SCHEDULE
    },
    'TB_PLAN_PERFORMANCE': {
        'ddl': CREATE_TB_PLAN_PERFORMANCE,
        'comments': COMMENT_TB_PLAN_PERFORMANCE
    },
    'TB_PLAN_WEIGHT': {
        'ddl': CREATE_TB_PLAN_WEIGHT,
        'comments': COMMENT_TB_PLAN_WEIGHT
    }
}

# 테이블 생성 순서 (FK 의존성 고려)
TABLE_CREATE_ORDER = [
    'TB_PLAN_MASTER',      # 1. 마스터 (독립)
    'TB_PLAN_DETAIL',      # 2. 상세
    'TB_PLAN_BUDGET',      # 3. 예산
    'TB_PLAN_SCHEDULE',    # 4. 일정
    'TB_PLAN_PERFORMANCE', # 5. 성과
    'TB_PLAN_WEIGHT'       # 6. 비중
]

# 테이블 삭제 순서 (FK 의존성 역순)
TABLE_DROP_ORDER = list(reversed(TABLE_CREATE_ORDER))

